from source.commands.commands_generator.commands_generator_base import CommandsGeneratorRegistry
from source.commands.commands_generator.commands_generator_base import CommandsGeneratorBase
from source.commands.commands_generator.commands_generator_intensivity_mvc.commands_generator_intensivity_controller import CommandsGeneratorIntensivityController