from source.image_filters_algorithms.algorithm_threshold_one.algorithm_threshold_one import AlgorithmThresholdOneController 
from source.image_filters_algorithms.algorithm_threshold_two.algorithm_threshold_two import AlgorithmThresholdTwoController
from source.image_filters_algorithms.algorithm_contour.algorithm_contour import AlgorithmContour